import Layout from '@/components/Layout';
import '@/styles/globals.css';
import Head from 'next/head';

export default function App({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Events APP</title>
				<meta name='description' content='generated by next app' />
			</Head>
			<Layout>
				<Component {...pageProps} />
			</Layout>
		</>
	);
}
